on:
  push:
    paths:
      - 'keyboard/**'
  pull_request:
    paths:
      - 'keyboard/**'
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
